### PR TITLE
Revert "README.Indonesia.md"

### PR DESCRIPTION
**Pull request by yukuku**
Reverts yukuku/ambilwarna#21

@bowotmf was just spamming the repo by using a machine-translated README.md.

### CODE REVIEW

**Comment by denisk20** [comment]
Ouch, thanks for catching this!

**Comment by yukuku** [comment]
Thanks @denisk20 for helping maintaining this repo :)

I have reported @bowotmf to Github.

**Comment by jayvdb** [comment]
I do not believe that @bowotmf used machine translation (_edit_ or, I am surprised and unhappy to learn that he used machine translation and didnt edit it).  He is Indonesian, and is just a beginner who _tried_ to join @BesutKode competition / training program , which required that they do a useful PR on a repository with 50+ stars.  He was [not successful](https://github.com/BesutKode/BesutKode.github.io/pulls?q=is%3Apr+author%3Abowotmf+is%3Aclosed) joining the program.

I do appreciate that an Indonesian translation of the README is not necessarily very helpful, and respect your decision to remove it.  I only wanted to clarify regarding his intentions were well meaning, but misdirected.  Also my apologies for your time being wasted; we try to prevent participants doing low-quality work in other peoples repositories, but with 650 registrations trying to get into the program, there have been a few who tried 'too hard' without sufficient time invested into learning tools and community.

**Comment by denisk20** [comment]
Thank you for clarifying it @jayvdb. Yeah, even assuming the translation is of decent quality it's hardly a must-have for this project :) If the task for the student is to do something useful then we can come up with a real task, such as making our color picker adaptable to material themes.

**Pull request merged**
